CREATE TABLE usuario (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nome_completo VARCHAR(100) NOT NULL,
	email VARCHAR(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	senha VARCHAR(512) NOT NULL,
    PRIMARY KEY(id)
);
