CREATE TABLE pessoa (
	id BIGINT NOTNULL
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(11) NOT NULL,

);

ALTER TABLE pessoa ADD CONSTRAINT PKPESSOA PRIMARY KEY (id);

CREATE SEQUENCE pessoa.seqpessoa INCREMENT BY 1;